import type { HeadwindConfig } from './types'
import { loadConfig } from 'bunfig'
import { tailwindPreflight } from './preflight'

export const defaultConfig: HeadwindConfig = {
  content: ['./src/**/*.{html,js,ts,jsx,tsx,stx}'],
  output: './dist/headwind.css',
  minify: true,
  watch: false,
  theme: {
    colors: {
      black: '#000',
      white: '#fff',
      gray: {
        50: '#f9fafb',
        100: '#f3f4f6',
        200: '#e5e7eb',
        300: '#d1d5db',
        400: '#9ca3af',
        500: '#6b7280',
        600: '#4b5563',
        700: '#374151',
        800: '#1f2937',
        900: '#111827',
      },
      red: {
        500: '#ef4444',
        700: '#b91c1c',
      },
      blue: {
        500: '#3b82f6',
      },
      green: {
        500: '#22c55e',
      },
      yellow: {
        100: '#fef9c3',
      },
    },
    spacing: {
      0: '0',
      px: '1px',
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
    },
    fontSize: {
      'xs': ['0.75rem', { lineHeight: '1rem' }],
      'sm': ['0.875rem', { lineHeight: '1.25rem' }],
      'base': ['1rem', { lineHeight: '1.5rem' }],
      'lg': ['1.125rem', { lineHeight: '1.75rem' }],
      'xl': ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
    },
    fontFamily: {
      sans: ['ui-sans-serif', 'system-ui', 'sans-serif'],
      serif: ['ui-serif', 'Georgia', 'serif'],
      mono: ['ui-monospace', 'monospace'],
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    borderRadius: {
      'none': '0',
      'sm': '0.125rem',
      'DEFAULT': '0.25rem',
      'md': '0.375rem',
      'lg': '0.5rem',
      'xl': '0.75rem',
      '2xl': '1rem',
      'full': '9999px',
    },
    boxShadow: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      none: 'none',
    },
  },
  shortcuts: {},
  rules: [],
  variants: {
    'responsive': true,
    'hover': true,
    'focus': true,
    'active': true,
    'disabled': true,
    'dark': true,
    'group': true,
    'peer': true,
    'before': true,
    'after': true,
    'marker': true,
    'first': true,
    'last': true,
    'odd': true,
    'even': true,
    'first-of-type': true,
    'last-of-type': true,
    'visited': true,
    'checked': true,
    'focus-within': true,
    'focus-visible': true,
    'placeholder': true,
    'selection': true,
    'file': true,
    'required': true,
    'valid': true,
    'invalid': true,
    'read-only': true,
    'autofill': true,
    'open': true,
    'closed': true,
    'empty': true,
    'enabled': true,
    'only': true,
    'target': true,
    'indeterminate': true,
    'default': true,
    'optional': true,
    'print': true,
    'rtl': true,
    'ltr': true,
    'motion-safe': true,
    'motion-reduce': true,
    'contrast-more': true,
    'contrast-less': true,
  },
  safelist: [],
  blocklist: [],
  preflights: [tailwindPreflight],
  presets: [],
}

// eslint-disable-next-line antfu/no-top-level-await
export const config: HeadwindConfig = await loadConfig({
  name: 'headwind',
  defaultConfig,
})
